#
# CAUTION: This file is automatically generated by HSM.
# Version: 
# Generate by U-BOOT v4.00.c
# Project description at http://www.monstr.eu/uboot/
#


TEXT_BASE = 0x1fc00000
CONFIG_SYS_TEXT_BASE = 0x1fc00000
